export const errors = {
  USER: {
    USER_EXISTS_ALREADY: 'USER_EXISTS_ALREADY',
    USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
    REGISTER_USER_ERROR: 'ERROR_REGISTER_NEW_USER',
  },
  VALIDATION: {
    EMAIL_IS_EMPTY: 'EMAIL_IS_EMPTY',
    PASSWORD_IS_EMPTY: 'PASSWORD_IS_EMPTY',
    PASSWORD_LENGTH_MUST_BE_MORE_THAN_8: 'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8',
    WRONG_PASSWORD: 'WRONG_PASSWORD',
    EMAIL_IS_IN_WRONG_FORMAT: 'EMAIL_IS_IN_WRONG_FORMAT',
    TOKEN_IS_EMPTY: 'TOKEN_IS_EMPTY',
  },
  GENERIC: {
    SOME_THING_WENT_WRONG: 'SOME_THING_WENT_WRONG',
  },
};
